server {
    listen 7600;
    server_name _;

    # React/Vite frontend
    location / {
        proxy_pass http://localhost:5173;
    }

    # Auth Service
    location /api/auth {
        proxy_pass http://localhost:5001;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    location /api/products {
        proxy_pass http://localhost:5002;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}