
services:
  auth-db:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  product-db:
    image: postgres:16
    container_name: product_postgres
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_password
      POSTGRES_DB: product_db
    ports:
      - "5434:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always


  auth-service:
    build: ./backend/auth-service 
    container_name: auth-container
    ports:
      - "5001:5001"
    env_file: 
      - ./backend/auth-service/.env.docker
    depends_on:
      - auth-db
    networks:
      - app-network
    restart: always

  product-service:
    build: ./backend/product-service 
    container_name: product-container
    ports:
      - "5002:5002"
    env_file: 
      - ./backend/product-service/.env.docker
    depends_on:
      - product-db
    networks:
      - app-network
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend-container
    env_file: 
      - ./frontend/.env.production
    ports:
      - "3020:80"
    depends_on:
      - auth-service
      - product-service
    networks:
      - app-network
    restart: always

volumes:
  auth_data:
  product_data:

networks:
  app-network:
    driver: bridge